# https://github.com/docker/build-push-action/issues/561#issuecomment-1054596444
# https://docs.docker.com/build/ci/github-actions/multi-platform/ 

name: build docker image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        imageos:
          - alpine
          - debian

    permissions:
      contents: read
      packages: write

    steps:
      - name: Get latest tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
    
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.tag }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
      - name: Build and push container images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_${{ matrix.imageos }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.imageos }}-${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max